---

linux_add_packages_cache_valid_time: 60
upgrade_all: false

#linux_add_packages_repositories:
#- repo:

#linux_add_packages_keys:
#- key:

#linux_add_packages_names:
#- name:

#linux_remove_packages_names:
#- name:
